// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: as.proto

package as;

public final class As {
  private As() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ASRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:as.ASRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string log_id = 1;</code>
     */
    String getLogId();
    /**
     * <code>string log_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getLogIdBytes();

    /**
     * <code>string user_id = 2;</code>
     */
    String getUserId();
    /**
     * <code>string user_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>.user_info.UserInfo user_info = 3;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>.user_info.UserInfo user_info = 3;</code>
     */
    user_info.UserInfoOuterClass.UserInfo getUserInfo();
    /**
     * <code>.user_info.UserInfo user_info = 3;</code>
     */
    user_info.UserInfoOuterClass.UserInfoOrBuilder getUserInfoOrBuilder();
  }
  /**
   * Protobuf type {@code as.ASRequest}
   */
  public  static final class ASRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:as.ASRequest)
      ASRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ASRequest.newBuilder() to construct.
    private ASRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ASRequest() {
      logId_ = "";
      userId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ASRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              logId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 26: {
              user_info.UserInfoOuterClass.UserInfo.Builder subBuilder = null;
              if (userInfo_ != null) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(user_info.UserInfoOuterClass.UserInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return As.internal_static_as_ASRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return As.internal_static_as_ASRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ASRequest.class, Builder.class);
    }

    public static final int LOG_ID_FIELD_NUMBER = 1;
    private volatile Object logId_;
    /**
     * <code>string log_id = 1;</code>
     */
    public String getLogId() {
      Object ref = logId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      }
    }
    /**
     * <code>string log_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      Object ref = logId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private volatile Object userId_;
    /**
     * <code>string user_id = 2;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_INFO_FIELD_NUMBER = 3;
    private user_info.UserInfoOuterClass.UserInfo userInfo_;
    /**
     * <code>.user_info.UserInfo user_info = 3;</code>
     */
    public boolean hasUserInfo() {
      return userInfo_ != null;
    }
    /**
     * <code>.user_info.UserInfo user_info = 3;</code>
     */
    public user_info.UserInfoOuterClass.UserInfo getUserInfo() {
      return userInfo_ == null ? user_info.UserInfoOuterClass.UserInfo.getDefaultInstance() : userInfo_;
    }
    /**
     * <code>.user_info.UserInfo user_info = 3;</code>
     */
    public user_info.UserInfoOuterClass.UserInfoOrBuilder getUserInfoOrBuilder() {
      return getUserInfo();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLogIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, logId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (userInfo_ != null) {
        output.writeMessage(3, getUserInfo());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLogIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, logId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (userInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUserInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ASRequest)) {
        return super.equals(obj);
      }
      ASRequest other = (ASRequest) obj;

      boolean result = true;
      result = result && getLogId()
          .equals(other.getLogId());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && (hasUserInfo() == other.hasUserInfo());
      if (hasUserInfo()) {
        result = result && getUserInfo()
            .equals(other.getUserInfo());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLogId().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      if (hasUserInfo()) {
        hash = (37 * hash) + USER_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getUserInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ASRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ASRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ASRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ASRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ASRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ASRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ASRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ASRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ASRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ASRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ASRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ASRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ASRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code as.ASRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:as.ASRequest)
        ASRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return As.internal_static_as_ASRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return As.internal_static_as_ASRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ASRequest.class, Builder.class);
      }

      // Construct using as.As.ASRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        logId_ = "";

        userId_ = "";

        if (userInfoBuilder_ == null) {
          userInfo_ = null;
        } else {
          userInfo_ = null;
          userInfoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return As.internal_static_as_ASRequest_descriptor;
      }

      public ASRequest getDefaultInstanceForType() {
        return ASRequest.getDefaultInstance();
      }

      public ASRequest build() {
        ASRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ASRequest buildPartial() {
        ASRequest result = new ASRequest(this);
        result.logId_ = logId_;
        result.userId_ = userId_;
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ASRequest) {
          return mergeFrom((ASRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ASRequest other) {
        if (other == ASRequest.getDefaultInstance()) return this;
        if (!other.getLogId().isEmpty()) {
          logId_ = other.logId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ASRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ASRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object logId_ = "";
      /**
       * <code>string log_id = 1;</code>
       */
      public String getLogId() {
        Object ref = logId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          logId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string log_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLogIdBytes() {
        Object ref = logId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          logId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string log_id = 1;</code>
       */
      public Builder setLogId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string log_id = 1;</code>
       */
      public Builder clearLogId() {
        
        logId_ = getDefaultInstance().getLogId();
        onChanged();
        return this;
      }
      /**
       * <code>string log_id = 1;</code>
       */
      public Builder setLogIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logId_ = value;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <code>string user_id = 2;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string user_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 2;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private user_info.UserInfoOuterClass.UserInfo userInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          user_info.UserInfoOuterClass.UserInfo, user_info.UserInfoOuterClass.UserInfo.Builder, user_info.UserInfoOuterClass.UserInfoOrBuilder> userInfoBuilder_;
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      public boolean hasUserInfo() {
        return userInfoBuilder_ != null || userInfo_ != null;
      }
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      public user_info.UserInfoOuterClass.UserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_ == null ? user_info.UserInfoOuterClass.UserInfo.getDefaultInstance() : userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      public Builder setUserInfo(user_info.UserInfoOuterClass.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      public Builder setUserInfo(
          user_info.UserInfoOuterClass.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      public Builder mergeUserInfo(user_info.UserInfoOuterClass.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (userInfo_ != null) {
            userInfo_ =
              user_info.UserInfoOuterClass.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = null;
          onChanged();
        } else {
          userInfo_ = null;
          userInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      public user_info.UserInfoOuterClass.UserInfo.Builder getUserInfoBuilder() {
        
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      public user_info.UserInfoOuterClass.UserInfoOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_ == null ?
              user_info.UserInfoOuterClass.UserInfo.getDefaultInstance() : userInfo_;
        }
      }
      /**
       * <code>.user_info.UserInfo user_info = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          user_info.UserInfoOuterClass.UserInfo, user_info.UserInfoOuterClass.UserInfo.Builder, user_info.UserInfoOuterClass.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              user_info.UserInfoOuterClass.UserInfo, user_info.UserInfoOuterClass.UserInfo.Builder, user_info.UserInfoOuterClass.UserInfoOrBuilder>(
                  getUserInfo(),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:as.ASRequest)
    }

    // @@protoc_insertion_point(class_scope:as.ASRequest)
    private static final ASRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ASRequest();
    }

    public static ASRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ASRequest>
        PARSER = new com.google.protobuf.AbstractParser<ASRequest>() {
      public ASRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ASRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ASRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ASRequest> getParserForType() {
      return PARSER;
    }

    public ASRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ASResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:as.ASResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.as.ASResponse.Error error = 1;</code>
     */
    boolean hasError();
    /**
     * <code>.as.ASResponse.Error error = 1;</code>
     */
    ASResponse.Error getError();
    /**
     * <code>.as.ASResponse.Error error = 1;</code>
     */
    ASResponse.ErrorOrBuilder getErrorOrBuilder();

    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    java.util.List<item_info.ItemInfoOuterClass.ItemInfo> 
        getItemInfosList();
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    item_info.ItemInfoOuterClass.ItemInfo getItemInfos(int index);
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    int getItemInfosCount();
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    java.util.List<? extends item_info.ItemInfoOuterClass.ItemInfoOrBuilder> 
        getItemInfosOrBuilderList();
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    item_info.ItemInfoOuterClass.ItemInfoOrBuilder getItemInfosOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code as.ASResponse}
   */
  public  static final class ASResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:as.ASResponse)
      ASResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ASResponse.newBuilder() to construct.
    private ASResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ASResponse() {
      itemInfos_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ASResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Error.Builder subBuilder = null;
              if (error_ != null) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(Error.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                itemInfos_ = new java.util.ArrayList<item_info.ItemInfoOuterClass.ItemInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              itemInfos_.add(
                  input.readMessage(item_info.ItemInfoOuterClass.ItemInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          itemInfos_ = java.util.Collections.unmodifiableList(itemInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return As.internal_static_as_ASResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return As.internal_static_as_ASResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ASResponse.class, Builder.class);
    }

    public interface ErrorOrBuilder extends
        // @@protoc_insertion_point(interface_extends:as.ASResponse.Error)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint32 code = 1;</code>
       */
      int getCode();

      /**
       * <code>string text = 2;</code>
       */
      String getText();
      /**
       * <code>string text = 2;</code>
       */
      com.google.protobuf.ByteString
          getTextBytes();
    }
    /**
     * Protobuf type {@code as.ASResponse.Error}
     */
    public  static final class Error extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:as.ASResponse.Error)
        ErrorOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Error.newBuilder() to construct.
      private Error(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Error() {
        code_ = 0;
        text_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Error(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                code_ = input.readUInt32();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                text_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return As.internal_static_as_ASResponse_Error_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return As.internal_static_as_ASResponse_Error_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Error.class, Builder.class);
      }

      public static final int CODE_FIELD_NUMBER = 1;
      private int code_;
      /**
       * <code>uint32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }

      public static final int TEXT_FIELD_NUMBER = 2;
      private volatile Object text_;
      /**
       * <code>string text = 2;</code>
       */
      public String getText() {
        Object ref = text_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          text_ = s;
          return s;
        }
      }
      /**
       * <code>string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (code_ != 0) {
          output.writeUInt32(1, code_);
        }
        if (!getTextBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, code_);
        }
        if (!getTextBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Error)) {
          return super.equals(obj);
        }
        Error other = (Error) obj;

        boolean result = true;
        result = result && (getCode()
            == other.getCode());
        result = result && getText()
            .equals(other.getText());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Error parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Error parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Error parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Error parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Error parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Error parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Error parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Error parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Error parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Error parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Error parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Error parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Error prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code as.ASResponse.Error}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:as.ASResponse.Error)
          ErrorOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return As.internal_static_as_ASResponse_Error_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return As.internal_static_as_ASResponse_Error_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Error.class, Builder.class);
        }

        // Construct using as.As.ASResponse.Error.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          code_ = 0;

          text_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return As.internal_static_as_ASResponse_Error_descriptor;
        }

        public Error getDefaultInstanceForType() {
          return Error.getDefaultInstance();
        }

        public Error build() {
          Error result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Error buildPartial() {
          Error result = new Error(this);
          result.code_ = code_;
          result.text_ = text_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Error) {
            return mergeFrom((Error)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Error other) {
          if (other == Error.getDefaultInstance()) return this;
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          if (!other.getText().isEmpty()) {
            text_ = other.text_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Error parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Error) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int code_ ;
        /**
         * <code>uint32 code = 1;</code>
         */
        public int getCode() {
          return code_;
        }
        /**
         * <code>uint32 code = 1;</code>
         */
        public Builder setCode(int value) {
          
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 code = 1;</code>
         */
        public Builder clearCode() {
          
          code_ = 0;
          onChanged();
          return this;
        }

        private Object text_ = "";
        /**
         * <code>string text = 2;</code>
         */
        public String getText() {
          Object ref = text_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            text_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string text = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTextBytes() {
          Object ref = text_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            text_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string text = 2;</code>
         */
        public Builder setText(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          text_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string text = 2;</code>
         */
        public Builder clearText() {
          
          text_ = getDefaultInstance().getText();
          onChanged();
          return this;
        }
        /**
         * <code>string text = 2;</code>
         */
        public Builder setTextBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          text_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:as.ASResponse.Error)
      }

      // @@protoc_insertion_point(class_scope:as.ASResponse.Error)
      private static final Error DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Error();
      }

      public static Error getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Error>
          PARSER = new com.google.protobuf.AbstractParser<Error>() {
        public Error parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Error(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Error> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Error> getParserForType() {
        return PARSER;
      }

      public Error getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ERROR_FIELD_NUMBER = 1;
    private Error error_;
    /**
     * <code>.as.ASResponse.Error error = 1;</code>
     */
    public boolean hasError() {
      return error_ != null;
    }
    /**
     * <code>.as.ASResponse.Error error = 1;</code>
     */
    public Error getError() {
      return error_ == null ? Error.getDefaultInstance() : error_;
    }
    /**
     * <code>.as.ASResponse.Error error = 1;</code>
     */
    public ErrorOrBuilder getErrorOrBuilder() {
      return getError();
    }

    public static final int ITEM_INFOS_FIELD_NUMBER = 2;
    private java.util.List<item_info.ItemInfoOuterClass.ItemInfo> itemInfos_;
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    public java.util.List<item_info.ItemInfoOuterClass.ItemInfo> getItemInfosList() {
      return itemInfos_;
    }
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    public java.util.List<? extends item_info.ItemInfoOuterClass.ItemInfoOrBuilder> 
        getItemInfosOrBuilderList() {
      return itemInfos_;
    }
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    public int getItemInfosCount() {
      return itemInfos_.size();
    }
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    public item_info.ItemInfoOuterClass.ItemInfo getItemInfos(int index) {
      return itemInfos_.get(index);
    }
    /**
     * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
     */
    public item_info.ItemInfoOuterClass.ItemInfoOrBuilder getItemInfosOrBuilder(
        int index) {
      return itemInfos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (error_ != null) {
        output.writeMessage(1, getError());
      }
      for (int i = 0; i < itemInfos_.size(); i++) {
        output.writeMessage(2, itemInfos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (error_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getError());
      }
      for (int i = 0; i < itemInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, itemInfos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ASResponse)) {
        return super.equals(obj);
      }
      ASResponse other = (ASResponse) obj;

      boolean result = true;
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && getError()
            .equals(other.getError());
      }
      result = result && getItemInfosList()
          .equals(other.getItemInfosList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      if (getItemInfosCount() > 0) {
        hash = (37 * hash) + ITEM_INFOS_FIELD_NUMBER;
        hash = (53 * hash) + getItemInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ASResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ASResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ASResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ASResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ASResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ASResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ASResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ASResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ASResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ASResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ASResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ASResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ASResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code as.ASResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:as.ASResponse)
        ASResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return As.internal_static_as_ASResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return As.internal_static_as_ASResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ASResponse.class, Builder.class);
      }

      // Construct using as.As.ASResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemInfosFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorBuilder_ == null) {
          error_ = null;
        } else {
          error_ = null;
          errorBuilder_ = null;
        }
        if (itemInfosBuilder_ == null) {
          itemInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemInfosBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return As.internal_static_as_ASResponse_descriptor;
      }

      public ASResponse getDefaultInstanceForType() {
        return ASResponse.getDefaultInstance();
      }

      public ASResponse build() {
        ASResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ASResponse buildPartial() {
        ASResponse result = new ASResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        if (itemInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            itemInfos_ = java.util.Collections.unmodifiableList(itemInfos_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.itemInfos_ = itemInfos_;
        } else {
          result.itemInfos_ = itemInfosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ASResponse) {
          return mergeFrom((ASResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ASResponse other) {
        if (other == ASResponse.getDefaultInstance()) return this;
        if (other.hasError()) {
          mergeError(other.getError());
        }
        if (itemInfosBuilder_ == null) {
          if (!other.itemInfos_.isEmpty()) {
            if (itemInfos_.isEmpty()) {
              itemInfos_ = other.itemInfos_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemInfosIsMutable();
              itemInfos_.addAll(other.itemInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.itemInfos_.isEmpty()) {
            if (itemInfosBuilder_.isEmpty()) {
              itemInfosBuilder_.dispose();
              itemInfosBuilder_ = null;
              itemInfos_ = other.itemInfos_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemInfosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemInfosFieldBuilder() : null;
            } else {
              itemInfosBuilder_.addAllMessages(other.itemInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ASResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ASResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Error error_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Error, Error.Builder, ErrorOrBuilder> errorBuilder_;
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      public boolean hasError() {
        return errorBuilder_ != null || error_ != null;
      }
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      public Error getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? Error.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      public Builder setError(Error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      public Builder setError(
          Error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      public Builder mergeError(Error value) {
        if (errorBuilder_ == null) {
          if (error_ != null) {
            error_ =
              Error.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = null;
          onChanged();
        } else {
          error_ = null;
          errorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      public Error.Builder getErrorBuilder() {
        
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      public ErrorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              Error.getDefaultInstance() : error_;
        }
      }
      /**
       * <code>.as.ASResponse.Error error = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Error, Error.Builder, ErrorOrBuilder>
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Error, Error.Builder, ErrorOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      private java.util.List<item_info.ItemInfoOuterClass.ItemInfo> itemInfos_ =
        java.util.Collections.emptyList();
      private void ensureItemInfosIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          itemInfos_ = new java.util.ArrayList<item_info.ItemInfoOuterClass.ItemInfo>(itemInfos_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          item_info.ItemInfoOuterClass.ItemInfo, item_info.ItemInfoOuterClass.ItemInfo.Builder, item_info.ItemInfoOuterClass.ItemInfoOrBuilder> itemInfosBuilder_;

      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public java.util.List<item_info.ItemInfoOuterClass.ItemInfo> getItemInfosList() {
        if (itemInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(itemInfos_);
        } else {
          return itemInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public int getItemInfosCount() {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.size();
        } else {
          return itemInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public item_info.ItemInfoOuterClass.ItemInfo getItemInfos(int index) {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.get(index);
        } else {
          return itemInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder setItemInfos(
          int index, item_info.ItemInfoOuterClass.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.set(index, value);
          onChanged();
        } else {
          itemInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder setItemInfos(
          int index, item_info.ItemInfoOuterClass.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder addItemInfos(item_info.ItemInfoOuterClass.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.add(value);
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder addItemInfos(
          int index, item_info.ItemInfoOuterClass.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.add(index, value);
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder addItemInfos(
          item_info.ItemInfoOuterClass.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.add(builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder addItemInfos(
          int index, item_info.ItemInfoOuterClass.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder addAllItemInfos(
          Iterable<? extends item_info.ItemInfoOuterClass.ItemInfo> values) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, itemInfos_);
          onChanged();
        } else {
          itemInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder clearItemInfos() {
        if (itemInfosBuilder_ == null) {
          itemInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public Builder removeItemInfos(int index) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.remove(index);
          onChanged();
        } else {
          itemInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public item_info.ItemInfoOuterClass.ItemInfo.Builder getItemInfosBuilder(
          int index) {
        return getItemInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public item_info.ItemInfoOuterClass.ItemInfoOrBuilder getItemInfosOrBuilder(
          int index) {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.get(index);  } else {
          return itemInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public java.util.List<? extends item_info.ItemInfoOuterClass.ItemInfoOrBuilder> 
           getItemInfosOrBuilderList() {
        if (itemInfosBuilder_ != null) {
          return itemInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(itemInfos_);
        }
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public item_info.ItemInfoOuterClass.ItemInfo.Builder addItemInfosBuilder() {
        return getItemInfosFieldBuilder().addBuilder(
            item_info.ItemInfoOuterClass.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public item_info.ItemInfoOuterClass.ItemInfo.Builder addItemInfosBuilder(
          int index) {
        return getItemInfosFieldBuilder().addBuilder(
            index, item_info.ItemInfoOuterClass.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .item_info.ItemInfo item_infos = 2;</code>
       */
      public java.util.List<item_info.ItemInfoOuterClass.ItemInfo.Builder> 
           getItemInfosBuilderList() {
        return getItemInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          item_info.ItemInfoOuterClass.ItemInfo, item_info.ItemInfoOuterClass.ItemInfo.Builder, item_info.ItemInfoOuterClass.ItemInfoOrBuilder> 
          getItemInfosFieldBuilder() {
        if (itemInfosBuilder_ == null) {
          itemInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              item_info.ItemInfoOuterClass.ItemInfo, item_info.ItemInfoOuterClass.ItemInfo.Builder, item_info.ItemInfoOuterClass.ItemInfoOrBuilder>(
                  itemInfos_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          itemInfos_ = null;
        }
        return itemInfosBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:as.ASResponse)
    }

    // @@protoc_insertion_point(class_scope:as.ASResponse)
    private static final ASResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ASResponse();
    }

    public static ASResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ASResponse>
        PARSER = new com.google.protobuf.AbstractParser<ASResponse>() {
      public ASResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ASResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ASResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ASResponse> getParserForType() {
      return PARSER;
    }

    public ASResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_as_ASRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_as_ASRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_as_ASResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_as_ASResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_as_ASResponse_Error_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_as_ASResponse_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\010as.proto\022\002as\032\017item_info.proto\032\017user_in" +
      "fo.proto\"T\n\tASRequest\022\016\n\006log_id\030\001 \001(\t\022\017\n" +
      "\007user_id\030\002 \001(\t\022&\n\tuser_info\030\003 \001(\0132\023.user" +
      "_info.UserInfo\"\177\n\nASResponse\022#\n\005error\030\001 " +
      "\001(\0132\024.as.ASResponse.Error\022\'\n\nitem_infos\030" +
      "\002 \003(\0132\023.item_info.ItemInfo\032#\n\005Error\022\014\n\004c" +
      "ode\030\001 \001(\r\022\014\n\004text\030\002 \001(\t25\n\tASService\022(\n\007" +
      "as_call\022\r.as.ASRequest\032\016.as.ASResponseB\003" +
      "\200\001\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          item_info.ItemInfoOuterClass.getDescriptor(),
          user_info.UserInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_as_ASRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_as_ASRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_as_ASRequest_descriptor,
        new String[] { "LogId", "UserId", "UserInfo", });
    internal_static_as_ASResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_as_ASResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_as_ASResponse_descriptor,
        new String[] { "Error", "ItemInfos", });
    internal_static_as_ASResponse_Error_descriptor =
      internal_static_as_ASResponse_descriptor.getNestedTypes().get(0);
    internal_static_as_ASResponse_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_as_ASResponse_Error_descriptor,
        new String[] { "Code", "Text", });
    item_info.ItemInfoOuterClass.getDescriptor();
    user_info.UserInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
