// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: item_info.proto

package item_info;

public final class ItemInfoOuterClass {
  private ItemInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItemInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:item_info.ItemInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sku_id = 1;</code>
     */
    String getSkuId();
    /**
     * <code>string sku_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSkuIdBytes();

    /**
     * <code>string brand = 2;</code>
     */
    String getBrand();
    /**
     * <code>string brand = 2;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string shopid = 3;</code>
     */
    String getShopid();
    /**
     * <code>string shopid = 3;</code>
     */
    com.google.protobuf.ByteString
        getShopidBytes();

    /**
     * <code>string cate = 4;</code>
     */
    String getCate();
    /**
     * <code>string cate = 4;</code>
     */
    com.google.protobuf.ByteString
        getCateBytes();

    /**
     * <code>float rank_score = 5;</code>
     */
    float getRankScore();
  }
  /**
   * Protobuf type {@code item_info.ItemInfo}
   */
  public  static final class ItemInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:item_info.ItemInfo)
      ItemInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemInfo.newBuilder() to construct.
    private ItemInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemInfo() {
      skuId_ = "";
      brand_ = "";
      shopid_ = "";
      cate_ = "";
      rankScore_ = 0F;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              skuId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              shopid_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              cate_ = s;
              break;
            }
            case 45: {

              rankScore_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ItemInfoOuterClass.internal_static_item_info_ItemInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ItemInfoOuterClass.internal_static_item_info_ItemInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ItemInfo.class, Builder.class);
    }

    public static final int SKU_ID_FIELD_NUMBER = 1;
    private volatile Object skuId_;
    /**
     * <code>string sku_id = 1;</code>
     */
    public String getSkuId() {
      Object ref = skuId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        skuId_ = s;
        return s;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes() {
      Object ref = skuId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        skuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 2;
    private volatile Object brand_;
    /**
     * <code>string brand = 2;</code>
     */
    public String getBrand() {
      Object ref = brand_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHOPID_FIELD_NUMBER = 3;
    private volatile Object shopid_;
    /**
     * <code>string shopid = 3;</code>
     */
    public String getShopid() {
      Object ref = shopid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        shopid_ = s;
        return s;
      }
    }
    /**
     * <code>string shopid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getShopidBytes() {
      Object ref = shopid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        shopid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATE_FIELD_NUMBER = 4;
    private volatile Object cate_;
    /**
     * <code>string cate = 4;</code>
     */
    public String getCate() {
      Object ref = cate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cate_ = s;
        return s;
      }
    }
    /**
     * <code>string cate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCateBytes() {
      Object ref = cate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RANK_SCORE_FIELD_NUMBER = 5;
    private float rankScore_;
    /**
     * <code>float rank_score = 5;</code>
     */
    public float getRankScore() {
      return rankScore_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSkuIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, skuId_);
      }
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, brand_);
      }
      if (!getShopidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, shopid_);
      }
      if (!getCateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cate_);
      }
      if (rankScore_ != 0F) {
        output.writeFloat(5, rankScore_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSkuIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, skuId_);
      }
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, brand_);
      }
      if (!getShopidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, shopid_);
      }
      if (!getCateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cate_);
      }
      if (rankScore_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, rankScore_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ItemInfo)) {
        return super.equals(obj);
      }
      ItemInfo other = (ItemInfo) obj;

      boolean result = true;
      result = result && getSkuId()
          .equals(other.getSkuId());
      result = result && getBrand()
          .equals(other.getBrand());
      result = result && getShopid()
          .equals(other.getShopid());
      result = result && getCate()
          .equals(other.getCate());
      result = result && (
          Float.floatToIntBits(getRankScore())
          == Float.floatToIntBits(
              other.getRankScore()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSkuId().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + SHOPID_FIELD_NUMBER;
      hash = (53 * hash) + getShopid().hashCode();
      hash = (37 * hash) + CATE_FIELD_NUMBER;
      hash = (53 * hash) + getCate().hashCode();
      hash = (37 * hash) + RANK_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRankScore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ItemInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ItemInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ItemInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code item_info.ItemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:item_info.ItemInfo)
        ItemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ItemInfoOuterClass.internal_static_item_info_ItemInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ItemInfoOuterClass.internal_static_item_info_ItemInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ItemInfo.class, Builder.class);
      }

      // Construct using item_info.ItemInfoOuterClass.ItemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        skuId_ = "";

        brand_ = "";

        shopid_ = "";

        cate_ = "";

        rankScore_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ItemInfoOuterClass.internal_static_item_info_ItemInfo_descriptor;
      }

      public ItemInfo getDefaultInstanceForType() {
        return ItemInfo.getDefaultInstance();
      }

      public ItemInfo build() {
        ItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ItemInfo buildPartial() {
        ItemInfo result = new ItemInfo(this);
        result.skuId_ = skuId_;
        result.brand_ = brand_;
        result.shopid_ = shopid_;
        result.cate_ = cate_;
        result.rankScore_ = rankScore_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ItemInfo) {
          return mergeFrom((ItemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ItemInfo other) {
        if (other == ItemInfo.getDefaultInstance()) return this;
        if (!other.getSkuId().isEmpty()) {
          skuId_ = other.skuId_;
          onChanged();
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getShopid().isEmpty()) {
          shopid_ = other.shopid_;
          onChanged();
        }
        if (!other.getCate().isEmpty()) {
          cate_ = other.cate_;
          onChanged();
        }
        if (other.getRankScore() != 0F) {
          setRankScore(other.getRankScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ItemInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ItemInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object skuId_ = "";
      /**
       * <code>string sku_id = 1;</code>
       */
      public String getSkuId() {
        Object ref = skuId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          skuId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sku_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSkuIdBytes() {
        Object ref = skuId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          skuId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sku_id = 1;</code>
       */
      public Builder setSkuId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sku_id = 1;</code>
       */
      public Builder clearSkuId() {
        
        skuId_ = getDefaultInstance().getSkuId();
        onChanged();
        return this;
      }
      /**
       * <code>string sku_id = 1;</code>
       */
      public Builder setSkuIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skuId_ = value;
        onChanged();
        return this;
      }

      private Object brand_ = "";
      /**
       * <code>string brand = 2;</code>
       */
      public String getBrand() {
        Object ref = brand_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string brand = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 2;</code>
       */
      public Builder setBrand(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 2;</code>
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 2;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private Object shopid_ = "";
      /**
       * <code>string shopid = 3;</code>
       */
      public String getShopid() {
        Object ref = shopid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          shopid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string shopid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getShopidBytes() {
        Object ref = shopid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          shopid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string shopid = 3;</code>
       */
      public Builder setShopid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shopid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string shopid = 3;</code>
       */
      public Builder clearShopid() {
        
        shopid_ = getDefaultInstance().getShopid();
        onChanged();
        return this;
      }
      /**
       * <code>string shopid = 3;</code>
       */
      public Builder setShopidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shopid_ = value;
        onChanged();
        return this;
      }

      private Object cate_ = "";
      /**
       * <code>string cate = 4;</code>
       */
      public String getCate() {
        Object ref = cate_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cate = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCateBytes() {
        Object ref = cate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cate = 4;</code>
       */
      public Builder setCate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cate = 4;</code>
       */
      public Builder clearCate() {
        
        cate_ = getDefaultInstance().getCate();
        onChanged();
        return this;
      }
      /**
       * <code>string cate = 4;</code>
       */
      public Builder setCateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cate_ = value;
        onChanged();
        return this;
      }

      private float rankScore_ ;
      /**
       * <code>float rank_score = 5;</code>
       */
      public float getRankScore() {
        return rankScore_;
      }
      /**
       * <code>float rank_score = 5;</code>
       */
      public Builder setRankScore(float value) {
        
        rankScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float rank_score = 5;</code>
       */
      public Builder clearRankScore() {
        
        rankScore_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:item_info.ItemInfo)
    }

    // @@protoc_insertion_point(class_scope:item_info.ItemInfo)
    private static final ItemInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ItemInfo();
    }

    public static ItemInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemInfo>
        PARSER = new com.google.protobuf.AbstractParser<ItemInfo>() {
      public ItemInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ItemInfo> getParserForType() {
      return PARSER;
    }

    public ItemInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_item_info_ItemInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_item_info_ItemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017item_info.proto\022\titem_info\"[\n\010ItemInfo" +
      "\022\016\n\006sku_id\030\001 \001(\t\022\r\n\005brand\030\002 \001(\t\022\016\n\006shopi" +
      "d\030\003 \001(\t\022\014\n\004cate\030\004 \001(\t\022\022\n\nrank_score\030\005 \001(" +
      "\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_item_info_ItemInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_item_info_ItemInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_item_info_ItemInfo_descriptor,
        new String[] { "SkuId", "Brand", "Shopid", "Cate", "RankScore", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
