# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: as.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import item_info_pb2 as item__info__pb2
import user_info_pb2 as user__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61s.proto\x12\x02\x61s\x1a\x0fitem_info.proto\x1a\x0fuser_info.proto\"T\n\tASRequest\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12&\n\tuser_info\x18\x03 \x01(\x0b\x32\x13.user_info.UserInfo\"\x7f\n\nASResponse\x12#\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x14.as.ASResponse.Error\x12\'\n\nitem_infos\x18\x02 \x03(\x0b\x32\x13.item_info.ItemInfo\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t25\n\tASService\x12(\n\x07\x61s_call\x12\r.as.ASRequest\x1a\x0e.as.ASResponseB\x03\x80\x01\x00\x62\x06proto3')



_ASREQUEST = DESCRIPTOR.message_types_by_name['ASRequest']
_ASRESPONSE = DESCRIPTOR.message_types_by_name['ASResponse']
_ASRESPONSE_ERROR = _ASRESPONSE.nested_types_by_name['Error']
ASRequest = _reflection.GeneratedProtocolMessageType('ASRequest', (_message.Message,), {
  'DESCRIPTOR' : _ASREQUEST,
  '__module__' : 'as_pb2'
  # @@protoc_insertion_point(class_scope:as.ASRequest)
  })
_sym_db.RegisterMessage(ASRequest)

ASResponse = _reflection.GeneratedProtocolMessageType('ASResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _ASRESPONSE_ERROR,
    '__module__' : 'as_pb2'
    # @@protoc_insertion_point(class_scope:as.ASResponse.Error)
    })
  ,
  'DESCRIPTOR' : _ASRESPONSE,
  '__module__' : 'as_pb2'
  # @@protoc_insertion_point(class_scope:as.ASResponse)
  })
_sym_db.RegisterMessage(ASResponse)
_sym_db.RegisterMessage(ASResponse.Error)

_ASSERVICE = DESCRIPTOR.services_by_name['ASService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\000'
  _ASREQUEST._serialized_start=50
  _ASREQUEST._serialized_end=134
  _ASRESPONSE._serialized_start=136
  _ASRESPONSE._serialized_end=263
  _ASRESPONSE_ERROR._serialized_start=228
  _ASRESPONSE_ERROR._serialized_end=263
  _ASSERVICE._serialized_start=265
  _ASSERVICE._serialized_end=318
# @@protoc_insertion_point(module_scope)
