# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cm_pb2 as cm__pb2


class CMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cm_call = channel.unary_unary(
                '/cm.CMService/cm_call',
                request_serializer=cm__pb2.CMRequest.SerializeToString,
                response_deserializer=cm__pb2.CMResponse.FromString,
                )


class CMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cm_call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cm_call': grpc.unary_unary_rpc_method_handler(
                    servicer.cm_call,
                    request_deserializer=cm__pb2.CMRequest.FromString,
                    response_serializer=cm__pb2.CMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cm.CMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cm_call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cm.CMService/cm_call',
            cm__pb2.CMRequest.SerializeToString,
            cm__pb2.CMResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
