# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import item_info_pb2 as item__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x63m.proto\x12\x02\x63m\x1a\x0fitem_info.proto\"-\n\tCMRequest\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x10\n\x08item_ids\x18\x02 \x03(\t\"\x7f\n\nCMResponse\x12#\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x14.cm.CMResponse.Error\x12\'\n\nitem_infos\x18\x02 \x03(\x0b\x32\x13.item_info.ItemInfo\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t25\n\tCMService\x12(\n\x07\x63m_call\x12\r.cm.CMRequest\x1a\x0e.cm.CMResponseB\x03\x80\x01\x00\x62\x06proto3')



_CMREQUEST = DESCRIPTOR.message_types_by_name['CMRequest']
_CMRESPONSE = DESCRIPTOR.message_types_by_name['CMResponse']
_CMRESPONSE_ERROR = _CMRESPONSE.nested_types_by_name['Error']
CMRequest = _reflection.GeneratedProtocolMessageType('CMRequest', (_message.Message,), {
  'DESCRIPTOR' : _CMREQUEST,
  '__module__' : 'cm_pb2'
  # @@protoc_insertion_point(class_scope:cm.CMRequest)
  })
_sym_db.RegisterMessage(CMRequest)

CMResponse = _reflection.GeneratedProtocolMessageType('CMResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _CMRESPONSE_ERROR,
    '__module__' : 'cm_pb2'
    # @@protoc_insertion_point(class_scope:cm.CMResponse.Error)
    })
  ,
  'DESCRIPTOR' : _CMRESPONSE,
  '__module__' : 'cm_pb2'
  # @@protoc_insertion_point(class_scope:cm.CMResponse)
  })
_sym_db.RegisterMessage(CMResponse)
_sym_db.RegisterMessage(CMResponse.Error)

_CMSERVICE = DESCRIPTOR.services_by_name['CMService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\000'
  _CMREQUEST._serialized_start=33
  _CMREQUEST._serialized_end=78
  _CMRESPONSE._serialized_start=80
  _CMRESPONSE._serialized_end=207
  _CMRESPONSE_ERROR._serialized_start=172
  _CMRESPONSE_ERROR._serialized_end=207
  _CMSERVICE._serialized_start=209
  _CMSERVICE._serialized_end=262
# @@protoc_insertion_point(module_scope)
