# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fitem_info.proto\x12\titem_info\"[\n\x08ItemInfo\x12\x0e\n\x06sku_id\x18\x01 \x01(\t\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\x0e\n\x06shopid\x18\x03 \x01(\t\x12\x0c\n\x04\x63\x61te\x18\x04 \x01(\t\x12\x12\n\nrank_score\x18\x05 \x01(\x02\x62\x06proto3')



_ITEMINFO = DESCRIPTOR.message_types_by_name['ItemInfo']
ItemInfo = _reflection.GeneratedProtocolMessageType('ItemInfo', (_message.Message,), {
  'DESCRIPTOR' : _ITEMINFO,
  '__module__' : 'item_info_pb2'
  # @@protoc_insertion_point(class_scope:item_info.ItemInfo)
  })
_sym_db.RegisterMessage(ItemInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMINFO._serialized_start=30
  _ITEMINFO._serialized_end=121
# @@protoc_insertion_point(module_scope)
