# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_info_pb2 as user__info__pb2
import item_info_pb2 as item__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrank.proto\x1a\x0fuser_info.proto\x1a\x0fitem_info.proto\"n\n\x0bRankRequest\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12&\n\tuser_info\x18\x02 \x01(\x0b\x32\x13.user_info.UserInfo\x12\'\n\nitem_infos\x18\x03 \x03(\x0b\x32\x13.item_info.ItemInfo\"\xae\x01\n\x0cRankResponse\x12\"\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x13.RankResponse.Error\x12,\n\x0bscore_pairs\x18\x02 \x03(\x0b\x32\x17.RankResponse.ScorePair\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x1a\'\n\tScorePair\x12\x0b\n\x03nid\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32:\n\x0bRankService\x12+\n\x0crank_predict\x12\x0c.RankRequest\x1a\r.RankResponseb\x06proto3')



_RANKREQUEST = DESCRIPTOR.message_types_by_name['RankRequest']
_RANKRESPONSE = DESCRIPTOR.message_types_by_name['RankResponse']
_RANKRESPONSE_ERROR = _RANKRESPONSE.nested_types_by_name['Error']
_RANKRESPONSE_SCOREPAIR = _RANKRESPONSE.nested_types_by_name['ScorePair']
RankRequest = _reflection.GeneratedProtocolMessageType('RankRequest', (_message.Message,), {
  'DESCRIPTOR' : _RANKREQUEST,
  '__module__' : 'rank_pb2'
  # @@protoc_insertion_point(class_scope:RankRequest)
  })
_sym_db.RegisterMessage(RankRequest)

RankResponse = _reflection.GeneratedProtocolMessageType('RankResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _RANKRESPONSE_ERROR,
    '__module__' : 'rank_pb2'
    # @@protoc_insertion_point(class_scope:RankResponse.Error)
    })
  ,

  'ScorePair' : _reflection.GeneratedProtocolMessageType('ScorePair', (_message.Message,), {
    'DESCRIPTOR' : _RANKRESPONSE_SCOREPAIR,
    '__module__' : 'rank_pb2'
    # @@protoc_insertion_point(class_scope:RankResponse.ScorePair)
    })
  ,
  'DESCRIPTOR' : _RANKRESPONSE,
  '__module__' : 'rank_pb2'
  # @@protoc_insertion_point(class_scope:RankResponse)
  })
_sym_db.RegisterMessage(RankResponse)
_sym_db.RegisterMessage(RankResponse.Error)
_sym_db.RegisterMessage(RankResponse.ScorePair)

_RANKSERVICE = DESCRIPTOR.services_by_name['RankService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANKREQUEST._serialized_start=48
  _RANKREQUEST._serialized_end=158
  _RANKRESPONSE._serialized_start=161
  _RANKRESPONSE._serialized_end=335
  _RANKRESPONSE_ERROR._serialized_start=259
  _RANKRESPONSE_ERROR._serialized_end=294
  _RANKRESPONSE_SCOREPAIR._serialized_start=296
  _RANKRESPONSE_SCOREPAIR._serialized_end=335
  _RANKSERVICE._serialized_start=337
  _RANKSERVICE._serialized_end=395
# @@protoc_insertion_point(module_scope)
