# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recall.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_info_pb2 as user__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecall.proto\x12\x06recall\x1a\x0fuser_info.proto\"q\n\rRecallRequest\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12&\n\tuser_info\x18\x02 \x01(\x0b\x32\x13.user_info.UserInfo\x12\x13\n\x0brecall_type\x18\x03 \x01(\t\x12\x13\n\x0brequest_num\x18\x04 \x01(\r\"\xc2\x01\n\x0eRecallResponse\x12+\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1c.recall.RecallResponse.Error\x12\x35\n\x0bscore_pairs\x18\x02 \x03(\x0b\x32 .recall.RecallResponse.ScorePair\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x1a\'\n\tScorePair\x12\x0b\n\x03nid\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32H\n\rRecallService\x12\x37\n\x06recall\x12\x15.recall.RecallRequest\x1a\x16.recall.RecallResponseB\x03\x80\x01\x00\x62\x06proto3')



_RECALLREQUEST = DESCRIPTOR.message_types_by_name['RecallRequest']
_RECALLRESPONSE = DESCRIPTOR.message_types_by_name['RecallResponse']
_RECALLRESPONSE_ERROR = _RECALLRESPONSE.nested_types_by_name['Error']
_RECALLRESPONSE_SCOREPAIR = _RECALLRESPONSE.nested_types_by_name['ScorePair']
RecallRequest = _reflection.GeneratedProtocolMessageType('RecallRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECALLREQUEST,
  '__module__' : 'recall_pb2'
  # @@protoc_insertion_point(class_scope:recall.RecallRequest)
  })
_sym_db.RegisterMessage(RecallRequest)

RecallResponse = _reflection.GeneratedProtocolMessageType('RecallResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _RECALLRESPONSE_ERROR,
    '__module__' : 'recall_pb2'
    # @@protoc_insertion_point(class_scope:recall.RecallResponse.Error)
    })
  ,

  'ScorePair' : _reflection.GeneratedProtocolMessageType('ScorePair', (_message.Message,), {
    'DESCRIPTOR' : _RECALLRESPONSE_SCOREPAIR,
    '__module__' : 'recall_pb2'
    # @@protoc_insertion_point(class_scope:recall.RecallResponse.ScorePair)
    })
  ,
  'DESCRIPTOR' : _RECALLRESPONSE,
  '__module__' : 'recall_pb2'
  # @@protoc_insertion_point(class_scope:recall.RecallResponse)
  })
_sym_db.RegisterMessage(RecallResponse)
_sym_db.RegisterMessage(RecallResponse.Error)
_sym_db.RegisterMessage(RecallResponse.ScorePair)

_RECALLSERVICE = DESCRIPTOR.services_by_name['RecallService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\000'
  _RECALLREQUEST._serialized_start=41
  _RECALLREQUEST._serialized_end=154
  _RECALLRESPONSE._serialized_start=157
  _RECALLRESPONSE._serialized_end=351
  _RECALLRESPONSE_ERROR._serialized_start=275
  _RECALLRESPONSE_ERROR._serialized_end=310
  _RECALLRESPONSE_SCOREPAIR._serialized_start=312
  _RECALLRESPONSE_SCOREPAIR._serialized_end=351
  _RECALLSERVICE._serialized_start=353
  _RECALLSERVICE._serialized_end=425
# @@protoc_insertion_point(module_scope)
