# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: um.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_info_pb2 as user__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08um.proto\x12\x02um\x1a\x0fuser_info.proto\"3\n\x10UserModelRequest\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\x8c\x01\n\x11UserModelResponse\x12*\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1b.um.UserModelResponse.Error\x12&\n\tuser_info\x18\x02 \x01(\x0b\x32\x13.user_info.UserInfo\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t2C\n\tUMService\x12\x36\n\x07um_call\x12\x14.um.UserModelRequest\x1a\x15.um.UserModelResponseB\x03\x80\x01\x00\x62\x06proto3')



_USERMODELREQUEST = DESCRIPTOR.message_types_by_name['UserModelRequest']
_USERMODELRESPONSE = DESCRIPTOR.message_types_by_name['UserModelResponse']
_USERMODELRESPONSE_ERROR = _USERMODELRESPONSE.nested_types_by_name['Error']
UserModelRequest = _reflection.GeneratedProtocolMessageType('UserModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERMODELREQUEST,
  '__module__' : 'um_pb2'
  # @@protoc_insertion_point(class_scope:um.UserModelRequest)
  })
_sym_db.RegisterMessage(UserModelRequest)

UserModelResponse = _reflection.GeneratedProtocolMessageType('UserModelResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _USERMODELRESPONSE_ERROR,
    '__module__' : 'um_pb2'
    # @@protoc_insertion_point(class_scope:um.UserModelResponse.Error)
    })
  ,
  'DESCRIPTOR' : _USERMODELRESPONSE,
  '__module__' : 'um_pb2'
  # @@protoc_insertion_point(class_scope:um.UserModelResponse)
  })
_sym_db.RegisterMessage(UserModelResponse)
_sym_db.RegisterMessage(UserModelResponse.Error)

_UMSERVICE = DESCRIPTOR.services_by_name['UMService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\000'
  _USERMODELREQUEST._serialized_start=33
  _USERMODELREQUEST._serialized_end=84
  _USERMODELRESPONSE._serialized_start=87
  _USERMODELRESPONSE._serialized_end=227
  _USERMODELRESPONSE_ERROR._serialized_start=192
  _USERMODELRESPONSE_ERROR._serialized_end=227
  _UMSERVICE._serialized_start=229
  _UMSERVICE._serialized_end=296
# @@protoc_insertion_point(module_scope)
