# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import um_pb2 as um__pb2


class UMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.um_call = channel.unary_unary(
                '/um.UMService/um_call',
                request_serializer=um__pb2.UserModelRequest.SerializeToString,
                response_deserializer=um__pb2.UserModelResponse.FromString,
                )


class UMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def um_call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'um_call': grpc.unary_unary_rpc_method_handler(
                    servicer.um_call,
                    request_deserializer=um__pb2.UserModelRequest.FromString,
                    response_serializer=um__pb2.UserModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'um.UMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def um_call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/um.UMService/um_call',
            um__pb2.UserModelRequest.SerializeToString,
            um__pb2.UserModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
