# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser_info.proto\x12\tuser_info\"z\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\t\x12\x0b\n\x03sex\x18\x03 \x01(\t\x12\x12\n\ncity_level\x18\x04 \x01(\t\x12\x10\n\x08province\x18\x05 \x01(\t\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x07 \x01(\tb\x06proto3')



_USERINFO = DESCRIPTOR.message_types_by_name['UserInfo']
UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'user_info_pb2'
  # @@protoc_insertion_point(class_scope:user_info.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINFO._serialized_start=30
  _USERINFO._serialized_end=152
# @@protoc_insertion_point(module_scope)
